name: Deploy frontend application
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # ... 其他步骤保持不变 ...
      - name: Build and push
        uses: docker/build-push-action@v6
        with:  # 修复缩进问题
          context: .
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/234-deploylab-frontend:latest" # 修复tags格式
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/frontend"
      
      - name: docker compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/frontend
            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose down
            docker compose pull
            docker compose up -d
            rm -rf /home/ubuntu/frontend
